# Generated by Django 4.2.5 on 2023-09-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fridges", "0002_alter_fridge_name_alter_fridge_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fridge",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="fridge",
            name="quantity",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="fridge",
            name="quantity_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("kg", "kg"),
                    ("g", "g"),
                    ("l", "l"),
                    ("ml", "ml"),
                    ("szt.", "szt."),
                    ("opak.", "opak."),
                ],
                max_length=5,
                null=True,
            ),
        ),
    ]
