# Generated by Django 4.2.5 on 2023-09-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recepies", "0002_recepie_preparation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recepie",
            name="preparation",
            field=models.TextField(blank=True, null=True),
        ),
    ]
