# Generated by Django 4.2.5 on 2023-09-10 10:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recepies", "0004_alter_recepie_preparation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recepie",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=20, null=True),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
