# Generated by Django 4.2.5 on 2023-09-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("quantity", models.CharField(max_length=5)),
                (
                    "quantity_type",
                    models.CharField(
                        choices=[
                            ("kg", "kg"),
                            ("g", "g"),
                            ("l", "l"),
                            ("ml", "ml"),
                            ("szt.", "szt."),
                            ("opak.", "opak."),
                        ],
                        default="",
                        max_length=5,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="ingredients",
        ),
    ]
