# Generated by Django 4.2.5 on 2023-09-13 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_ingredient_remove_recipe_ingredients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="quantity_type",
            field=models.CharField(
                choices=[
                    ("", ""),
                    ("kg", "kg"),
                    ("g", "g"),
                    ("l", "l"),
                    ("ml", "ml"),
                    ("szt.", "szt."),
                    ("opak.", "opak."),
                ],
                default="",
                max_length=5,
            ),
        ),
        migrations.CreateModel(
            name="RecipeIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.CharField(max_length=5)),
                (
                    "amount_type",
                    models.CharField(
                        choices=[
                            ("", ""),
                            ("kg", "kg"),
                            ("g", "g"),
                            ("l", "l"),
                            ("ml", "ml"),
                            ("szt.", "szt."),
                            ("opak.", "opak."),
                        ],
                        default="",
                        max_length=5,
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recipes.ingredient",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="recipes.recipe"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                through="recipes.RecipeIngredient", to="recipes.ingredient"
            ),
        ),
    ]
