# Generated by Django 4.2.5 on 2023-09-15 17:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0003_alter_ingredient_quantity_type_recipeingredient_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipeingredient",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="recipeingredient",
            name="amount_type",
        ),
    ]
