# Generated by Django 4.2.5 on 2023-09-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0003_alter_recipe_preparation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="preparation",
            field=models.TextField(default=""),
        ),
    ]
