# Generated by Django 4.2.5 on 2023-09-15 19:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0004_remove_recipeingredient_amount_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="user_fk",
            new_name="user",
        ),
    ]
