# Generated by Django 4.2.5 on 2023-09-10 11:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0005_alter_recepie_tags"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recepie",
            old_name="name",
            new_name="recepie_name",
        ),
    ]
