# Generated by Django 4.2.5 on 2023-09-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0006_rename_name_recepie_recepie_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recepie",
            name="ingredients",
            field=models.JSONField(),
        ),
    ]
